# fly.toml app configuration file generated for restless-cherry-209 on 2023-07-26T22:20:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-cherry-209"
primary_region = "yul"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
